PROJECT_NAME = "subtitle-3"
VALIDATION_BATCH_SIZE = 128

DATA_DIR = "/home/CLAP/data"
AUDIO_FILES_DIR = f"{DATA_DIR}/audio_files"
TRAIN_CSV = f"{DATA_DIR}/train.csv"
VALIDATION_CSV = f"{DATA_DIR}/validation.csv"

DEFAULT_LEARNING_RATE = 1e-3
DEFAULT_WEIGHT_DECAY = 0.01
DEFAULT_BATCH_SIZE = 128
DEFAULT_NUM_EPOCHS = 40
DEFAULT_IS_AUGMENTED = False
DEFAULT_CONFIG_VERSION = "505DB528" 